routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CodexController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\TypeController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use RealRashid\SweetAlert\Facades\Alert;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/home', [DashboardController::class, 'index'])->name('home');

    /* Route Type Controller */
    Route::resource('/type', TypeController::class);
    Route::get('serverside_type', [TypeController::class, 'getServersideType'])->name('getServersideType');

    /* Route Codex Controller */
    Route::resource('/codex', CodexController::class);
    Route::get('serverside_codex', [CodexController::class, 'getServersideCodex'])->name('getServersideCodex');

    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('/profile/{id}/edit', [AuthController::class, 'formProfile'])->name('profile.edit');
    Route::put('/profile/{id}', [AuthController::class, 'profile'])->name('profile.update');

    Route::get('/setting/{id}/edit', [AuthController::class, 'formSetting'])->name('setting.edit');
    Route::put('/setting/{id}', [AuthController::class, 'setting'])->name('setting.update');

    Route::get('/{any}', function () {
        Alert::error('Error', 'Anda tidak diizinkan untuk mengakses halaman ini!');
        return redirect()->route('home');
    })->where('any', '^(?!login|register|type|codex).*$');
});

/* Route Register */
Route::middleware(['guest'])->group(function () {
    Route::get('/register', [AuthController::class, 'formRegister'])->name('register.index');
    Route::post('/register', [AuthController::class, 'register'])->name('register');

    /* Route Login */
    Route::get('/login', [AuthController::class, 'formLogin'])->name('login.index');
    Route::post('/login', [AuthController::class, 'login'])->name('login');
});

app/Http/Controllers/TypeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Type;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Support\Facades\Validator;
use Yajra\DataTables\Facades\DataTables;

class TypeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $data = [
            'title' => 'Master Data Tipe Koding!'
        ];

        return view('./master/type/get', $data);
    }

    public function getServersideType()
    {
        $user = Auth::user();
        $data = Type::select(['uuid', 'user_id', 'slug', 'type_koding','colors', 'created_at']);

        return DataTables::of($data)
            ->addIndexColumn()
            ->editColumn('created_at', function ($row) {
                return Carbon::parse($row->created_at)->format('Y-m-d H:i:s');
            })
            ->addColumn('DT_RowIndex', function ($row) {
                return $row->uuid;
            })
            ->addColumn('aksi', function ($row) use ($user) {
                $btn = '';
                if ($row->canEdit($user)) {
                    $btn .= '<a href="' . route('type.edit', $row->slug) . '" class="btn btn-sm btn-primary mr-1"><i class="fas fa-edit"></i> Edit</a>';
                } else {
                    $btn .= '<span class="badge badge-danger">Maaf, anda bukan pembuat dari master <b>Tipe Koding</b> ini!</span>';
                }

                if ($row->canDelete($user)) {
                    $btn .= '<form action="' . route('type.destroy', $row->slug) . '" method="post" class="d-inline-block">
                            ' . method_field('DELETE') . '
                            ' . csrf_field() . '
                            <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm(\'Apakah Anda yakin ingin menghapus data ini?\')"><i class="fas fa-trash"></i> Delete</button>
                        </form>';
                } else {

                }

                return $btn;
            })
            ->rawColumns(['aksi'])
            ->make(true);
    }




    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $data = [
            'title' => 'Master Data Tipe Koding!',
        ];

        return view('./master/type/add', $data);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'type_koding' => 'required|unique:types',
        ]);

        if ($validator->fails()) {
            Alert::error('Error', implode('<br>', $validator->errors()->all()));
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $type = new Type;
        $type->uuid = Str::uuid();
        $type->user_id = Auth::user()->id;
        $type->type_koding = $request->input('type_koding');
        $type->slug = Str::slug($request->input('type_koding'));
        $type->colors = $request->input('colors');

        try {
            $type->save();
            Alert::success('Success', 'Mantap');
            $redirect = redirect()->route('type.index');
        } catch (\Exception $e) {
            Alert::error('Error', 'Ooppsss: ' . $e->getMessage());
            $redirect = redirect()->back();
        }

        return $redirect;
    }



    /**
     * Display the specified resource.
     */

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Type $type)
    {
        if ($type->user_id !== Auth::id()) {
            return abort(403);
        } else {
            $data = [
                'title' => 'Master Data Tipe Koding!',
                'type' => $type
            ];

            return view('./master/type/edit', $data);
        }
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Type $type)
    {
        $validator = Validator::make($request->all(), [
            'type_koding' => [$this->isUpdate(), 'string'],
            'colors' => [$this->isUpdate(), 'string'],
        ]);

        if ($validator->fails()) {
            Alert::error('Error', implode('<br>', $validator->errors()->all()));
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $type->type_koding = $request->input('type_koding');
        $type->slug = Str::slug($request->input('type_koding'));
        $type->colors = $request->input('colors');

        try {
            $type->save();
            Alert::success('Success', 'Mantap');
            $redirect = redirect()->route('type.index');
        } catch (\Exception $e) {
            Alert::error('Error', 'Ooppsss: ' . $e->getMessage());
            $redirect = redirect()->back();
        }

        return $redirect;
    }

    public function isUpdate()
    {
        return request()->isMethod('POST') ? 'required' : 'sometimes';
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Type $type)
    {
        try {
            $type->delete();
            Alert::success('Success', 'Data berhasil dihapus');
        } catch (\Exception $e) {
            Alert::error('Error', 'Ooppsss: ' . $e->getMessage());
        }

        return redirect()->route('type.index');
    }


}

resources/views/master/type/add.blade.php
@extends('welcome')

@section('content')
    @section('title')
        <h1 class="h3 mb-0 text-gray-800 font-weight-bolder">{{ $title ? $title : 'Ooppsss!' }}</h1>
    @endsection

    <div class="col-md-12">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <h5 class="font-weight-bolder">Tambah Tipe Koding!</h5>
                <a href="/type" class="btn btn-secondary btn-sm">Kembali</a>
            </div>
            <div class="card-body">
                <div class="col-md-4">
                    <form action="{{ route('type.store') }}" method="POST">
                        @csrf
                        <div class="mb-3">
                          <label for="type_koding" class="form-label">Tipe Koding</label>
                          <input type="text" class="form-control" id="type_koding" name="type_koding" placeholder="Masukkan Nilai Type Koding..." required autocomplete="false">
                        </div>
                        <div class="mb-3">
                          <label for="colors" class="form-label">Warna</label>
                          <input type="color" class="form-control" id="colors" name="colors" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/master/type/edit.blade.php
@extends('welcome')

@section('content')
    @section('title')
        <h1 class="h3 mb-0 text-gray-800 font-weight-bolder">{{ $title ? $title : 'Ooppsss!' }}</h1>
    @endsection

    <div class="col-md-12">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <h5 class="font-weight-bolder">Ubah Tipe Koding!</h5>
                <a href="/type" class="btn btn-secondary btn-sm">Kembali</a>
            </div>
            <div class="card-body">
                <div class="col-md-4">
                    <form action="{{ route('type.update', ['type' => $type->slug]) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="mb-3">
                          <label for="type_koding" class="form-label">Tipe Koding</label>
                          <input type="text" class="form-control" id="type_koding" name="type_koding" placeholder="Masukkan Nilai Type Koding..." required autocomplete="false" value="{{ $type->type_koding }}">
                          <div class="mb-3">
                            <label for="colors" class="form-label">Warna</label>
                            <input type="color" class="form-control" id="colors" name="colors" required value="{{ old('colors', $type->colors) }}">
                          </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/master/type/get.blade.php
@extends('welcome')

@section('content')
    @section('title')
        <h1 class="h3 mb-0 text-gray-800 font-weight-bolder">{{ $title ? $title : 'Something Wrong!' }}</h1>
    @endsection

    <div class="col-md-12">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Master Tipe Koding</h6>
                <a href="type/create" class="btn btn-primary btn-sm">Tambah</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered dataTable">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Type Koding</th>
                                <th>Created At</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
<script>
    $(function() {
        $('.dataTable').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{{ route('getServersideType') }}',
            columns: [
                { data: 'DT_RowIndex', name: 'DT_RowIndex'},
                { data: 'type_koding', name: 'type_koding', render: function(data, type, row) {
                    return '<span class="badge" style="background-color: ' + row.colors + '; color: white;">' + data + '</span>';
                } },
                { data: 'created_at', name: 'created_at' },
                { data: 'aksi', name: 'aksi', orderable: false, searchable: false }
            ]
        });
    });

</script>
@endpush