routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CodexController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\TypeController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use RealRashid\SweetAlert\Facades\Alert;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/home', [DashboardController::class, 'index'])->name('home');

    /* Route Type Controller */
    Route::resource('/type', TypeController::class);
    Route::get('serverside_type', [TypeController::class, 'getServersideType'])->name('getServersideType');

    /* Route Codex Controller */
    Route::resource('/codex', CodexController::class);
    Route::get('serverside_codex', [CodexController::class, 'getServersideCodex'])->name('getServersideCodex');

    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('/profile/{id}/edit', [AuthController::class, 'formProfile'])->name('profile.edit');
    Route::put('/profile/{id}', [AuthController::class, 'profile'])->name('profile.update');

    Route::get('/setting/{id}/edit', [AuthController::class, 'formSetting'])->name('setting.edit');
    Route::put('/setting/{id}', [AuthController::class, 'setting'])->name('setting.update');

    Route::get('/{any}', function () {
        Alert::error('Error', 'Anda tidak diizinkan untuk mengakses halaman ini!');
        return redirect()->route('home');
    })->where('any', '^(?!login|register|type|codex).*$');
});

/* Route Register */
Route::middleware(['guest'])->group(function () {
    Route::get('/register', [AuthController::class, 'formRegister'])->name('register.index');
    Route::post('/register', [AuthController::class, 'register'])->name('register');

    /* Route Login */
    Route::get('/login', [AuthController::class, 'formLogin'])->name('login.index');
    Route::post('/login', [AuthController::class, 'login'])->name('login');
});

app/Models/Codex.php
<?php

namespace App\Models;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Codex extends Model
{
    use HasFactory;

    protected $primaryKey = 'uuid';
    public $incrementing = false;
    protected $keyType = 'string';

    protected $fillable = [
        'type_uuid',
        'judul',
        'slug',
        'keterangan'
    ];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function setSlugAttribute($value)
    {
        $this->attributes['slug'] = Str::slug($value);
    }

    protected $casts = [
        'created_at' => 'datetime',
    ];

    public function types()
    {
        return $this->belongsTo(Type::class, 'type_uuid', 'uuid');
    }

}

app/Http/Controllers/CodexController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use App\Models\Type;
use App\Models\Codex;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;
use Yajra\DataTables\Facades\DataTables;
use App\Http\Requests\UpdateCodexRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class CodexController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $data = [
            'title'     => 'Koleksi Koding',
            'codexes'   => Codex::latest()->get()
        ];

        return view('content.codex.get', $data);
    }

    public function getServersideCodex()
    {
        $data = Codex::leftJoin('types', 'types.uuid', '=', 'codexes.type_uuid')
        ->select('codexes.uuid', 'codexes.type_uuid', 'types.uuid', 'types.type_koding', 'types.colors', 'codexes.judul', 'codexes.slug', 'codexes.keterangan', 'codexes.created_at');

        return DataTables::of($data)
            ->addIndexColumn()
            ->editColumn('created_at', function ($row) {
                return Carbon::parse($row->created_at)->format('Y-m-d H:i:s');
            })
            ->addColumn('DT_RowIndex', function ($row) {
                return $row->uuid;
            })
            ->addColumn('aksi', function ($row) {
                $user_id = auth()->user()->id;
                $btn = '<a href="' . route('codex.show', $row->slug) . '" class="btn btn-sm btn-info mr-1"><i class="fas fa-eye"></i> View</a>';
                if ($row->types->user_id == $user_id) {
                    $btn .= '<a href="' . route('codex.edit', $row->slug) . '" class="btn btn-sm btn-primary mr-1"><i class="fas fa-edit"></i> Edit</a>';
                    $btn .= '<form action="' . route('codex.destroy', $row->slug) . '" method="post" class="d-inline-block">
                        ' . method_field('DELETE') . '
                        ' . csrf_field() . '
                        <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm(\'Apakah Anda yakin ingin menghapus data ini?\')"><i class="fas fa-trash"></i> Delete</button>
                    </form>';
                }

                return $btn;
            })
            ->rawColumns(['aksi'])
            ->make(true);
    }



    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $user_id = auth()->user()->id;

        $data = [
            'title' => 'Koleksi Koding',
            'types' => Type::where('user_id', $user_id)->latest()->get()
        ];

        return view('content.codex.add', $data);
    }


    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'type_uuid' => 'required',
            'judul' => 'required|unique:codexes',
            'keterangan' => 'required'
        ]);

        if ($validator->fails()) {
            Alert::error('Error', implode('<br>', $validator->errors()->all()));
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $codex = new Codex;
        $codex->uuid = Str::uuid();
        $codex->type_uuid = $request->input('type_uuid');
        $codex->judul = $request->input('judul');
        $codex->slug = Str::slug($request->input('judul'));
        $codex->keterangan = $request->input('keterangan');

        try {
            $codex->save();
            Alert::success('Success', 'Mantap');
            $redirect = redirect()->route('codex.index');
        } catch (\Exception $e) {
            Alert::error('Error', 'Ooppsss: ' . $e->getMessage());
            $redirect = redirect()->back();
        }

        return $redirect;
    }

    /**
     * Display the specified resource.
     */
    public function show(Codex $codex)
    {
        $query = Codex::join('types', 'codexes.type_uuid', '=', 'types.uuid')
                    ->select('codexes.*', 'types.type_koding')
                    ->where('codexes.uuid', $codex->uuid)
                    ->first();

        $data = [
            'title'     => 'Koleksi Koding',
            'codex'     => $query
        ];

        return view('content.codex.show', $data);
    }


    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Codex $codex)
    {
        $user_id = auth()->user()->id;

        $data = [
            'title'     => 'Koleksi Koding',
            'types'     => Type::where('user_id', $user_id)->latest()->get(),
            'codex'     => $codex
        ];

        return view('content.codex.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Codex $codex)
    {
        $validator = Validator::make($request->all(), [
            'type_uuid' => [$this->isUpdate()],
            'judul' => [$this->isUpdate()],
            'keterangan' => [$this->isUpdate()]
        ]);

        if ($validator->fails()) {
            Alert::error('Error', implode('<br>', $validator->errors()->all()));
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $codex->type_uuid = $request->input('type_uuid');
        $codex->judul = $request->input('judul');
        $codex->slug = Str::slug($request->input('judul'));
        $codex->keterangan = $request->input('keterangan');

        try {
            $codex->save();
            Alert::success('Success', 'Mantap');
            $redirect = redirect()->route('codex.index');
        } catch (\Exception $e) {
            Alert::error('Error', 'Ooppsss: ' . $e->getMessage());
            $redirect = redirect()->back();
        }

        return $redirect;
    }

    /**
     * Mengembalikan nilai 'required' jika permintaan HTTP saat ini adalah metode POST, dan 'sometimes' jika bukan POST.
     *
     * @return string
     */
    public function isUpdate(): string {
        return request()->isMethod('POST') ? 'required' : 'sometimes';
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Codex $codex)
    {
        try {
            $codex->delete();
            Alert::success('Success', 'Data berhasil dihapus');
        } catch (\Exception $e) {
            Alert::error('Error', 'Ooppsss: ' . $e->getMessage());
        }

        return redirect()->route('codex.index');
    }
}

resources/views/content/codex/add.blade.php
@extends('welcome')

@section('content')
    @section('title')
        <h1 class="h3 mb-0 text-gray-800 font-weight-bolder">{{ $title ? $title : 'Ooppsss!' }}</h1>
    @endsection

    <div class="col-md-12">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <h5 class="font-weight-bolder">Tambah Tipe Koding!</h5>
                <a href="/codex" class="btn btn-secondary btn-sm">Kembali</a>
            </div>
            <div class="card-body">
                <form action="{{ route('codex.store') }}" method="POST">
                    @csrf
                    <div class="col-md-4">
                        <div class="mb-3">
                          <label for="type_uuid" class="form-label">Tipe Koding</label>
                          <select name="type_uuid" id="type_uuid" class="form-control typeSelect">
                            <option value="0" selected>Pilih Tipe</option>
                            @foreach ($types as $type)
                                <option value="{{ $type->uuid }}">{{ $type->type_koding }}</option>
                            @endforeach
                          </select>
                        </div>
                        <div class="md-12">
                            <label for="judul" class="form-label">Judul</label>
                            <input type="text" name="judul" id="judul" class="form-control" placeholder="Masukkan judul..." required autocomplete="false" autofocus>
                        </div>
                    </div>
                    <div class="col-md-8 my-4">
                        <div class="md-12">
                            <label for="keterangan" class="form-label">Keterangan</label>
                            <textarea name="keterangan" class="my-editor form-control" id="my-editor" cols="30" rows="10"></textarea>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </form>
            </div>
        </div>
    </div>

@endsection

@push('scripts')
<script>
    CKEDITOR.replace('my-editor', {
        startupMode: 'source',
        removePlugins: 'elementspath,resize,link,unlink,pastefromword,scayt,image,flash,find,replace,selectall,form,checkbox,radiobutton,textfield,textarea,button,select,hiddenfield,underline,strikethrough,subscript,superscript,indent,outdent,blockquote,createDiv,stylescombo,format,font,fontSize,color,textTransform,justify,indentblock,bidi,about,maximize,showblocks,table',
        removeButtons: 'Bold,Italic,Underline,Strike,Subscript,Superscript,NumberedList,BulletedList,Outdent,Indent,Blockquote,JustifyLeft,JustifyCenter,JustifyRight,JustifyBlock,Undo,Redo,Scayt,Image,Flash,Table,HorizontalRule,SpecialChar,PageBreak,RemoveFormat,Paste,PasteText'
      });

      $('.typeSelect').select2();

</script>
@endpush

resources/views/content/codex/edit.blade.php
@extends('welcome')

@section('content')
    @section('title')
        <h1 class="h3 mb-0 text-gray-800 font-weight-bolder">{{ $title ? $title : 'Ooppsss!' }}</h1>
    @endsection

    <div class="col-md-12">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <h5 class="font-weight-bolder">Ubah Koding!</h5>
                <a href="/codex" class="btn btn-secondary btn-sm">Kembali</a>
            </div>
            <div class="card-body">
                <form action="{{ route('codex.update', ['codex' => $codex->slug]) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="col-md-4">
                        <div class="mb-3">
                          <label for="type_uuid" class="form-label">Tipe Koding</label>
                          <select name="type_uuid" id="type_uuid" class="form-control selectType">
                            <option value="0" {{ old('type_uuid', $codex->type_uuid) == 0 ? 'selected' : '' }}>Pilih Tipe</option>
                            @foreach ($types as $type)
                               <option value="{{ $type->uuid }}" {{ old('type_uuid', $codex->type_uuid) == $type->uuid ? 'selected' : '' }}>{{ $type->type_koding }}</option>
                            @endforeach
                         </select>


                        </div>
                        <div class="md-12">
                            <label for="judul" class="form-label">Judul</label>
                            <input type="text" name="judul" id="judul" class="form-control" placeholder="Masukkan judul..." required autocomplete="false" autofocus value="{{ old('judul', $codex->judul) }}">
                        </div>
                    </div>
                    <div class="col-md-8 my-4">
                        <div class="md-12">
                            <label for="keterangan" class="form-label">Keterangan</label>
                            <textarea name="keterangan" class="my-editor form-control {{ $errors->has('keterangan') ? 'is-invalid' : '' }}" id="my-editor" cols="30" rows="10">{{ old('keterangan', $codex->keterangan) }}</textarea>
                            @if ($errors->has('keterangan'))
                            <div class="invalid-feedback">{{ $errors->first('keterangan') }}</div>
                            @endif
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </form>
            </div>
        </div>
    </div>

@endsection

@push('scripts')
<script>
    CKEDITOR.replace('my-editor', {
        startupMode: 'source',
        removePlugins: 'elementspath,resize,link,unlink,pastefromword,scayt,image,flash,find,replace,selectall,form,checkbox,radiobutton,textfield,textarea,button,select,hiddenfield,underline,strikethrough,subscript,superscript,indent,outdent,blockquote,createDiv,stylescombo,format,font,fontSize,color,textTransform,justify,indentblock,bidi,about,maximize,showblocks,table',
        removeButtons: 'Bold,Italic,Underline,Strike,Subscript,Superscript,NumberedList,BulletedList,Outdent,Indent,Blockquote,JustifyLeft,JustifyCenter,JustifyRight,JustifyBlock,Undo,Redo,Scayt,Image,Flash,Table,HorizontalRule,SpecialChar,PageBreak,RemoveFormat,Paste,PasteText'
      });

      $('.selectType').select2();

</script>
@endpush

resources/views/content/codex/get.blade.php
@extends('welcome')

@section('content')
    @section('title')
        <h1 class="h3 mb-0 text-gray-800 font-weight-bolder">{{ $title ? $title : 'Something Wrong!' }}</h1>
    @endsection

    <div class="col-md-12">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Koleksi Kodingku</h6>
                <a href="codex/create" class="btn btn-primary btn-sm">Tambah</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered dataTable">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Type Koding</th>
                                <th>Judul</th>
                                <th>Created At</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
<script>
    $(function() {
        $('.dataTable').DataTable({
            processing: true,
            serverSide: true,
            search: true,
            ajax: '{{ route('getServersideCodex') }}',
            columns: [
                { data: 'DT_RowIndex', name: 'DT_RowIndex'},
                { data: 'type_koding', name: 'types.type_koding', render: function(data, type, row) {
                    return '<span class="badge" style="background-color: ' + row.colors + '; color: white;">' + data + '</span>';
                } },
                { data: 'judul', name: 'judul' },
                { data: 'created_at', name: 'created_at' },
                { data: 'aksi', name: 'aksi', orderable: false, searchable: false }
            ]
        });
    });
</script>
@endpush

resources/views/content/codex/show.blade.php
@extends('welcome')

@section('content')
    @section('title')
        <h1 class="h3 mb-0 text-gray-800 font-weight-bolder">{{ $title ? $title : 'Something Wrong!' }}</h1>
    @endsection

    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <a href="{{ route('codex.index') }}" class="btn btn-secondary">Kembali</a>
            </div>
            <div class="card-body">
              <h3 class="card-title">{{ $codex->judul }}</h3>
              <p class="card-text"><span class="badge badge-warning">{{ $codex->type_koding }}</span></p>
                <div class="position-relative">
                    <pre><code id="my-code" class="language-{{ $codex->type_koding }}">{{ $codex->keterangan }}</code></pre>
                </div>
                <button onclick="copyCode('my-code')" class="btn btn-primary">Copy</button>
            </div>
        </div>
    </div>

@endsection
@push('scripts')
    <script>
        var clipboard = new ClipboardJS('.btn');

        function copyCode(elementId) {
            var element = document.getElementById(elementId);
            var range = document.createRange();
            range.selectNode(element);
            window.getSelection().removeAllRanges();
            window.getSelection().addRange(range);
            document.execCommand("copy");
            window.getSelection().removeAllRanges();
            Swal.fire({
                icon: 'success',
                title: 'Berhasil',
                text: 'Kode berhasil dicopy!',
            });
        }
    </script>
@endpush